import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './components/Providers'
import NavBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Notas App',
  description: 'Generated by Juan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})
{
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-darkTertiary dark:text-slate-300`}>
        <Providers>

          <NavBar />
          {children}

        </Providers>
      </body>
    </html>
  )
}
